disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: ''

external:
  donate: "https://www.paypal.com/ca/fundraiser/charity/3908200"
  register: "https://forms.gle/DwyGzKbb2qShb2xR9"
  youtube: "https://www.youtube.com/@wtcbc2009"
  facebook: "https://www.facebook.com/westcbc"
  instagram: "https://www.instagram.com/wtcbc_nissi"
  library: "https://docs.google.com/spreadsheets/d/1syDUBBzYitW--mOiyGB4Uyy7K5kqV9M7TuTDlhjStLI/edit?usp=sharing"

nav_zh:
  - {name: "主页", url: "/"}
  - {name: "关于我们", url: "/aboutus/"}
  - {name: "聚会信息", url: "/fellowship/"}
  - {name: "英文崇拜", url: "/englishservice/"}
  - {name: "尼西学生团契", url: "/耶和华尼西学生团契/"}
  - {name: "图书馆", url: "/library/"}
  - {name: "联系我们", url: "/contactus/"}

nav_en:
  - {name: "Home", url: "/en/"}
  - {name: "About", url: "/en/aboutus/"}
  - {name: "Groups", url: "/en/fellowship/"}
  - {name: "English Service", url: "/en/englishservice/"}
  - {name: "Nissi Fellowship", url: "/en/耶和华尼西学生团契/"}
  - {name: "Library", url: "/en/library/"}
  - {name: "Contact", url: "/en/contactus/"}

pagination:
  next_page: '下一页'
  previous_page: '上一页'

sharing_button_prompt: '自由分享这个消息吧！'
related_posts: '您可能喜欢...'
post_date_prefix: '写于'
